
#ifndef garde_elite_h
#define garde_elite_h


// Garde Elite
#define PROBA_GARDE_ELITE_1 1200
#define PROBA_GARDE_ELITE_2 900
#define PROBA_GARDE_ELITE_3 600
#define PROBA_GARDE_ELITE_4 550
#define PROBA_GARDE_ELITE_5 500
#define PROBA_GARDE_ELITE_6 450
#define PROBA_GARDE_ELITE_SALLE_HORDE 25


#define INTELL_GARDE_ELITE_DE_BASE 1
#define GARDE_ELITE_PROBA_AUGMENTER_INTELL_1 10
#define GARDE_ELITE_PROBA_AUGMENTER_INTELL_2 8
#define GARDE_ELITE_PROBA_AUGMENTER_INTELL_3 5
#define GARDE_ELITE_PROBA_AUGMENTER_INTELL_4 3
#define GARDE_ELITE_PROBA_AUGMENTER_INTELL_5 2
#define GARDE_ELITE_PROBA_AUGMENTER_INTELL_6 1

#define GARDE_ELITE_VITESSE_MAX 1


#define VARIATION_GARDE_ELITE_VITESSE_1 (3 + rand() % 2)
#define VARIATION_GARDE_ELITE_VITESSE_2 3
#define VARIATION_GARDE_ELITE_VITESSE_3 (2 + rand() % 2)
#define VARIATION_GARDE_ELITE_VITESSE_4 2
#define VARIATION_GARDE_ELITE_VITESSE_5 (1 + rand() % 2)
#define VARIATION_GARDE_ELITE_VITESSE_6 1

#define GARDE_ELITE_VISION_MIN_1 7
#define GARDE_ELITE_VISION_MIN_2 8
#define GARDE_ELITE_VISION_MIN_3 9
#define GARDE_ELITE_VISION_MIN_4 10
#define GARDE_ELITE_VISION_MIN_5 11
#define GARDE_ELITE_VISION_MIN_6 11

#define VARIATION_GARDE_ELITE_VISION 4


#endif /* garde_elite_h */
