
#ifndef garde_h
#define garde_h


// Garde
#define PROBA_GARDE_1 110
#define PROBA_GARDE_2 130
#define PROBA_GARDE_3 150
#define PROBA_GARDE_4 170
#define PROBA_GARDE_5 190
#define PROBA_GARDE_6 200

#define INTELL_GARDE_DE_BASE 0
#define GARDE_PROBA_AUGMENTER_INTELL_1 10
#define GARDE_PROBA_AUGMENTER_INTELL_2 7
#define GARDE_PROBA_AUGMENTER_INTELL_3 5
#define GARDE_PROBA_AUGMENTER_INTELL_4 3
#define GARDE_PROBA_AUGMENTER_INTELL_5 2
#define GARDE_PROBA_AUGMENTER_INTELL_6 1

#define GARDE_VITESSE_MAX 1

#define VARIATION_GARDE_VITESSE 4

#define GARDE_VISION_MIN_1 7
#define GARDE_VISION_MIN_2 8
#define GARDE_VISION_MIN_3 9
#define GARDE_VISION_MIN_4 10
#define GARDE_VISION_MIN_5 11
#define GARDE_VISION_MIN_6 12

#define VARIATION_GARDE_VISION 5


#endif /* garde_h */
