
#ifndef slum_h
#define slum_h


// Gros Slim
#define PROBA_GROS_SLIM_1 1000000
#define PROBA_GROS_SLIM_2 1000000
#define PROBA_GROS_SLIM_3 1000000
#define PROBA_GROS_SLIM_4 15000
#define PROBA_GROS_SLIM_5 8000
#define PROBA_GROS_SLIM_6 7500


#define INTELL_GROS_SLIM_DE_BASE 0

#define GROS_SLIM_VITESSE_MAX 10

#define VARIATION_GROS_SLIM_VITESSE 10

#define GROS_SLIM_VISION_MIN 1

#define GROS_SLIM_PROBA_ATTAQUE 70
#define DISTANCE_MIN_ATTAQUE_GROS_SLIM 15

#define GROS_SLIM_DISCRETION 70
#define VARIATION_GROS_SLIM_DISCRETION 50


#endif /* slum_h */
