
#ifndef mage_de_glace_h
#define mage_de_glace_h


// Mage de glace
#define PROBA_MAGE_DE_GLACE_1 10000000
#define PROBA_MAGE_DE_GLACE_2 10000000
#define PROBA_MAGE_DE_GLACE_3 10000
#define PROBA_MAGE_DE_GLACE_4 7500
#define PROBA_MAGE_DE_GLACE_5 6000
#define PROBA_MAGE_DE_GLACE_6 5500


#define INTELL_MAGE_DE_GLACE_DE_BASE 3

#define MAGE_DE_GLACE_VITESSE_MAX 2

#define MAGE_DE_GLACE_VISION_MIN_1 10
#define MAGE_DE_GLACE_VISION_MIN_2 11
#define MAGE_DE_GLACE_VISION_MIN_3 12
#define MAGE_DE_GLACE_VISION_MIN_4 13
#define MAGE_DE_GLACE_VISION_MIN_5 14
#define MAGE_DE_GLACE_VISION_MIN_6 15

#define VARIATION_MAGE_DE_GLACE_VISION 10

#define MAGE_DE_GLACE_PROBA_ATTAQUE 28
#define DISTANCE_MIN_ATTAQUE_MAGE_DE_GLACE 5
#define MAGE_DE_GLACE_DUREE_GEL 18

#endif /* mage_de_glace_h */
